export const mockEvents = [
  {
    id: "1",
    slug: "midnight-symphony-orchestra",
    title: "Midnight Symphony Orchestra",
    category: "Music",
    date: "2024-10-24",
    location: "Jakarta Convention Center",
    price: 450000,
    availableSeats: 120,
    totalSeats: 1500,
    imageColor: "from-pink-500 via-rose-500 to-orange-400",
    isFeatured: true,
    image: "https://picsum.photos/seed/midnight/800/1000",
  },
  {
    id: "2",
    slug: "ventix-innovation-summit",
    title: "Ventix Innovation Summit",
    category: "Tech",
    date: "2024-11-15",
    location: "Global Tech Hub, BSD",
    price: 1250000,
    availableSeats: 60,
    totalSeats: 800,
    imageColor: "from-indigo-500 via-blue-500 to-cyan-400",
    isFeatured: true,
    image: "https://picsum.photos/seed/tech/800/1000",
  },
  {
    id: "3",
    slug: "sunset-rooftop-mixer",
    title: "Sunset Rooftop Mixer",
    category: "Social",
    date: "2024-12-02",
    location: "Sky Garden Lounge",
    price: 250000,
    availableSeats: 42,
    totalSeats: 200,
    imageColor: "from-amber-500 via-orange-500 to-red-400",
    isFeatured: false,
    image: "https://picsum.photos/seed/rooftop/800/1000",
  },
  {
    id: "4",
    slug: "ui-ux-masterclass-2025",
    title: "UI/UX Masterclass 2025",
    category: "Workshop",
    date: "2025-01-10",
    location: "Creative Lab Studio",
    price: 850000,
    availableSeats: 18,
    totalSeats: 40,
    imageColor: "from-amber-500 via-orange-500 to-red-400",
    isFeatured: false,
    image: "https://picsum.photos/seed/workshop/800/1000",
  },
  {
    id: "5",
    slug: "starlight-symphony-electronic-2024",
    title: "Starlight Symphony: Electronic Edition 2024",
    category: "Concert",
    tags: ["CONCERT", "EXCLUSIVE"],
    date: "2024-10-24",
    time: "19:00",
    location: "Jakarta International Stadium",
    venue: "Grand Arena, Hall A",
    price: 750000,
    lineup: [
      { time: "19:00", title: "Opening Act: Neon Vesper", desc: "Atmospheric ambient warm-up" },
      { time: "20:30", title: "The Orchestral Synthesis", desc: "Main performance with 40-piece live orchestra" },
      { time: "22:00", title: "Midnight Rave Segment", desc: "High-tempo digital performance" },
    ],
    organizer: "Ventix Prime Events",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEkStNx3dd_FBPu5B3LYQAJBS52PnCW3-dPOPJqgs_YEudAsSAqBGpLcaYaXbNXvGNAd4KbE4B4X7u9afQjFPXZjYoJkA6ljsDyDCkYMPUD85yx-ea3eMoTrw18-4_iMrVijTNySOnwVAmP_f0xiDnC1irPXLgwidra02nTQfZtVnt2gVBnV2RhAL21bGJL_VulECqdDkeImegImj226y-oUGgMQnL-q_2MDd-59KixiWEnpFW1egnkgEZ2peP96fDtIeEHDrIH8Df",
  },
];

export default mockEvents;
